export const colors = {
  "surface-container-high": "#e6e9e7",
  "on-surface": "#191c1b",
  "primary-fixed": "#a3f69c",
  "secondary-container": "#9cf49c",
  "inverse-on-surface": "#eff1ef",
  "on-tertiary": "#ffffff",
  "on-primary-fixed": "#002204",
  "tertiary-fixed": "#ffd9e2",
  "on-secondary": "#ffffff",
  "outline-variant": "#bfcaba",
  "on-primary-container": "#cbffc2",
  "error-container": "#ffdad6",
  "surface-container-low": "#f2f4f2",
  "on-tertiary-fixed": "#3f001c",
  "on-secondary-container": "#19722b",
  "on-tertiary-container": "#ffedf0",
  "on-error": "#ffffff",
  "tertiary": "#923357",
  "secondary-fixed-dim": "#83da85",
  "primary-fixed-dim": "#88d982",
  "on-primary-fixed-variant": "#005312",
  "tertiary-fixed-dim": "#ffb1c7",
  "inverse-primary": "#88d982",
  "surface-variant": "#e1e3e1",
  "surface-bright": "#f8faf8",
  "error": "#ba1a1a",
  "on-surface-variant": "#40493d",
  "on-error-container": "#93000a",
  "secondary-fixed": "#9ff79f",
  "surface-container-highest": "#e1e3e1",
  "surface-container": "#eceeec",
  "on-secondary-fixed-variant": "#005318",
  "on-primary": "#ffffff",
  "tertiary-container": "#b14b6f",
  "on-secondary-fixed": "#002105",
  "outline": "#707a6c",
  "on-background": "#191c1b",
  "primary-container": "#2e7d32",
  "background": "#f8faf8",
  "surface-tint": "#1b6d24",
  "inverse-surface": "#2e3130",
  "secondary": "#126d27",
  "on-tertiary-fixed-variant": "#7f2448",
  "surface": "#f8faf8",
  "surface-container-lowest": "#ffffff",
  "surface-dim": "#d8dad9",
  "primary": "#0d631b"
};

export const typography = {
  headlineLg: { fontSize: 32, lineHeight: 40, fontWeight: '700' as const },
  headlineLgMobile: { fontSize: 28, lineHeight: 36, fontWeight: '700' as const },
  headlineMd: { fontSize: 24, lineHeight: 32, fontWeight: '600' as const },
  headlineSm: { fontSize: 20, lineHeight: 28, fontWeight: '600' as const },
  bodyLg: { fontSize: 18, lineHeight: 28, fontWeight: '400' as const },
  bodyMd: { fontSize: 16, lineHeight: 24, fontWeight: '400' as const },
  labelLg: { fontSize: 16, lineHeight: 24, fontWeight: '600' as const },
  labelMd: { fontSize: 14, lineHeight: 20, fontWeight: '500' as const },
};

export const spacing = {
  stackLg: 24,
  stackMd: 16,
  stackSm: 8,
  marginMobile: 20,
  marginDesktop: 40,
  gutter: 16,
  touchTargetMin: 48,
};
